import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "../src/styles/globals.css";


import Main from "./main";

import "../icon.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Roshan Patel",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Pass children as the page content */}

        <Main page={children} />
      </body>
    </html>
  );
}
